// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class LibDgo {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LibDgo(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LibDgo.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void dgo_InitPort(
    ffi.Pointer<ffi.Void> apiDLData,
    int sendPortKey,
    bool isDefault,
  ) {
    return _dgo_InitPort(
      apiDLData,
      sendPortKey,
      isDefault,
    );
  }

  late final _dgo_InitPortPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Void>, Dart_Port_DL, ffi.Bool)>>('dgo_InitPort');
  late final _dgo_InitPort = _dgo_InitPortPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>, int, bool)>();
}

typedef Dart_Port_DL = ffi.Int64;
